Feat/user controllers
isadorabk/mealee-server pull request #3
Opened 2018-08-15 19:15 UTC by isadorabk

my mainly concern is if the authentication strategy with jwt is well implemented....

2018-08-16 13:51 UTC, arol requested changes

2018-08-16 13:51 UTC, arol commented on controllers/user.controller.js
> +    const user = await this.User.findOne({
`ctx.user` is already the result of this same query made in the `authorization` middleware. Just grab `ctx.user`.

2018-08-16 13:51 UTC, arol commented on tests/user.test.js
> +'use strict';
The name is ambiguous, it looks like you're testing the user model.

2018-08-16 13:51 UTC, arol commented on controllers/user.controller.js
> +        email: body.email,
Don't use the body, use the `authorization` header.

2018-08-16 15:21 UTC, isadorabk commented on controllers/user.controller.js
> +        email: body.email,
But for the sign in the user doesn't have yet a token (it's generated when he signs in, not when he is created. Actually, this was one of the discussions yesterday with Marco when you were out, because I didn't know when to generate the token: if when the user is created, when he signs in or both. And the conclusion was that the sign in is actually a POST and you only generate the token in the sign in....)

2018-08-16 15:25 UTC, isadorabk commented
implemented all the changes but the one for the sign in (see my comment there)

2018-08-16 19:52 UTC, isadorabk commented
new jwt strategy implemented

2018-08-17 07:53 UTC, arol commented on controllers/user.controller.js
> +        email: body.email,
Ok we talked about it, but just to keep record of the conversation.
This is the sign in, no token required yet. This should follow Basic Authentication and the authorization data should be sent through the `Authorization` Header.

2018-08-17 07:56 UTC, arol submitted a review, later dismissed
Good job

2018-08-17 08:34 UTC, isadorabk commented
merge conflicts solved 🎉🎉🎉

2018-08-17 08:45 UTC, nickschoey approved these changes
Again, this is not my will. My life is in danger. Pliz help!

2018-08-17 08:49 UTC, merged