Feat/models
isadorabk/mealee-server pull request #4
Opened 2018-08-16 08:18 UTC by isadorabk

Set up db models for all tables

2018-08-16 13:59 UTC, arol requested changes

2018-08-16 13:59 UTC, arol commented on models/recipe.js
> +    Recipe.belongsToMany(models.Measure, {
Here you're saying that the `Recipe` has many `Measures`, I think it's the `recipe_ingredient` the one that has a measure.

2018-08-16 19:52 UTC, isadorabk commented
changes made

2018-08-17 07:57 UTC, arol approved these changes

2018-08-17 08:22 UTC, merged