Feat/pre set data controller
isadorabk/mealee-server pull request #6
Opened 2018-08-17 10:03 UTC by isadorabk

Controllers for get measures and get ingredients type.

2018-08-17 17:54 UTC, arol requested changes
Because of the route name, keep consistent, all plural.

2018-08-17 17:54 UTC, arol commented on controllers/ingredients.type.controller.js
> +        return res;
```js
ctx.body = ingredientsType.map(el => el.dataValues);
```

2018-08-17 17:54 UTC, arol commented on routes/routes.js
> +router.get('/ingredient-type', authMiddleware, ingredientsTypeController.getIngredientsType);
`/ingredient-types`

2018-08-17 17:54 UTC, arol commented on controllers/measures.controller.js
> +      ctx.body = measures.map(el => {
Same.

2018-08-18 11:20 UTC, isadorabk commented
Changes requested implemented :)

2018-08-20 07:25 UTC, arol approved these changes

2018-08-20 09:17 UTC, merged